### ISSUE TITLE
注释问题

### ISSUE THREAD

**Issue by forzeny** [yanhaijing/template.js#11]
html注释会在dom结构显示，可以不显示吗？还有其他注释方式？
比如bdtmpl <%* *%>

**Comment by yanhaijing** [comment]
注释这个目前有两种，js的和html的，没有第三种，待添加

**Comment by yxuecheng** [comment]
ok

**Comment by Chuyue0** [comment]
可使用js注释，如下：
<%/* 这里是注释 */%>
注释问题我还想问下，在‘<td><%=list[i].id%></td>’使用的时候会报’childNode‘错，注释中不能在包含模板内容吗？

**Comment by yanhaijing** [comment]
@Chuyue0 
1. 如果使用预编译工具的花，js注释和html注释都会输出出来，上面提到的注释指的是不会编译出来那种，得添加一个特殊语法，比如：
```
<*% xxxx %*>
```
2. 注释中不能包含模版内容，因为这是一个正则模版，没有上下文，没有语法树，不能做到识别注释。。。
