### ISSUE TITLE
fis预编译无法使用registerFunction？

### ISSUE THREAD

**Issue by mobei** [yanhaijing/template.js#13]
使用registerFunction之后，在fis项目里面，通过__inline方式获取tpl，然后执行tpl({})的时候提示通过registerFunction的方式注册的方法未定义。不知道这种方式下怎么使用。求助，谢谢！

**Comment by mobei** [comment]
我发现fis-parser-template依赖的是0.6.1的template，所以没有这个功能。。。

**Comment by yanhaijing** [comment]
是的，这个功能还没开发。。。

**Comment by yanhaijing** [comment]
没想到你竟然用到了，有兴趣贡献个 pr不

**Comment by mobei** [comment]
觉得这个功能挺好，很有用，注册了几个发现fis还不支持.....，有兴趣啊，等忙过这几天好好研究学习下😄
发自网易邮箱大师
在2017年04月26日 22:22，颜海镜 写道： 没想到你竟然用到了，有兴趣贡献个 pr不

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yanhaijing/template.js","title":"yanhaijing/template.js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yanhaijing/template.js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yanhaijing in #13: 没想到你竟然用到了，有兴趣贡献个 pr不"}],"action":{"name":"View Issue","url":"https://github.com/yanhaijing/template.js/issues/13#issuecomment-297424107"}}}

**Comment by yanhaijing** [comment]
@mobei templatejs v2.x 已经支持了
