### ISSUE TITLE
function template(tpl, data)

### ISSUE THREAD

**Issue by sjzjams** [yanhaijing/template.js#15]
function template(tpl, data)点击分页再次调用这个方法， tpl是undefined这个应该如何处理？

**Comment by yanhaijing** [comment]
很抱歉，我不是太明白

**Comment by sjzjams** [comment]
页面初次加载有数据，然后我ajax请求再绑定的时候模板就是undefinde了，然后我就搞成只要是undefinde的时候就给它吧tpl赋值。
`function template(tpl, data,tplval) {
        if (typeof tpl !== 'string') {
            if(tplval==="producttpl")
            {
                tpl=producttmp();
            }
        }
        var fn = compile(tpl);
        if (!isObject(data)) {
            return fn;
        }
        return fn(data);
    }
    function producttmp() {
        return '<%for (var i = 0; i < list.length; i++) {%>'
            +'<%var percentvalue = percent(list[i].bidTotal,list[i].available);%>'
            +'<tr>'
            +'<td><%:=list[i].bidName%></td>'
           ....
            +'<td class="tab-button">立即</td>'
            +'</tr>'
            +'<%}%>';
    }`

**Comment by yanhaijing** [comment]
tplval 这个是你自己改了源代码吗？

**Comment by sjzjams** [comment]
恩
