### ISSUE TITLE
tmpl文件里的img src路径，fis在编译时不会识别处理？

### ISSUE THREAD

**Issue by alloovee** [yanhaijing/template.js#16]
tmpl文件里的img src路径，fis在编译时不会识别处理？
比如`img src="/modules/forum/pages/img/folder_old.gif"` ，如果写在html页面，fis编译后会输出
`img src="/static/forum/pages/img/folder_old.gif"`

但是如果写在*.tmpl文件里了，fis编译时，不会识别和处理该img。

亲，请问如何让fis处理tmpl里的img src路径? 

期待回复，谢谢！

**Comment by yanhaijing** [comment]
fis只能处理html和css里的路径，js的路径是不能处理的，tmpl最终要编译为js，所以方法同js

js中只需给字符串加上fis内置处理函数即可

    __uri('path')

tmpl中需要如下处理，或者在js中传入处理之后的路径

    <#=__uri('path')#>

**Comment by alloovee** [comment]
感谢回复~~
1、在js中先__uri处理路径，当做参数传入tmpl是OK的；
2、在tmpl 文件中直接使用 <#= __uri('path') #>不行，template.js报错，提示__uri is not defined

fis 配置如下：
// ------ 配置前端模版 使用template.js
fis.match('**.tmpl', {
    parser: fis.plugin('template', {
        sTag: '<#',
        eTag: '#>',
        global: 'template'
    }),
    isJsLike: true,
    release: false
});

针对问题2，请看看是否可以在tmpl里使用 __uri，谢谢。

**Comment by yanhaijing** [comment]
ok感谢反馈
