### ISSUE TITLE
自带rem?

### ISSUE THREAD

**Issue by JunedanVan** [yanhaijing/template.js#17]
请问是自带rem吗？怎么我的字会根据屏幕大小跟着变，但是我看盒子里的数字却没有变。。。
![image](https://user-images.githubusercontent.com/24771641/29517348-429ee7e8-86a7-11e7-92ea-26e8ba294ac8.png)
![image](https://user-images.githubusercontent.com/24771641/29517354-48e32484-86a7-11e7-8b44-e122bb5ea924.png)

**Comment by yanhaijing** [comment]
你可以用开发者工具，查看对应元素的css，和写到html里的元素灭有区别，肯定是不带rem的
