### ISSUE TITLE
在webpack里面编译报错

### ISSUE THREAD

**Issue by horou-sk** [yanhaijing/template.js#19]
![image](https://user-images.githubusercontent.com/10435269/31650245-0c6d92fe-b349-11e7-83fa-9e96f0572a59.png)
![image](https://user-images.githubusercontent.com/10435269/31650260-1f497fbe-b349-11e7-807b-bfc8a10273cf.png)
![image](https://user-images.githubusercontent.com/10435269/31650273-2bfe608a-b349-11e7-857f-b7e60509fe44.png)

**Comment by yanhaijing** [comment]
可否提供一个demo？我运行一下？这里有个example 我试过是没有问题的
https://github.com/yanhaijing/template-loader

**Comment by yanhaijing** [comment]
收到

**Comment by yanhaijing** [comment]
<img width="482" alt="wx20171018-110746 2x" src="https://user-images.githubusercontent.com/3192087/31699341-0ec3ae78-b388-11e7-84f3-2a0c38bea8a2.png">

我这里编译成功了哈，浏览器预览也ok

**Comment by horou-sk** [comment]
你没改啥吗？我这边运行不起

**Comment by horou-sk** [comment]
![image](https://user-images.githubusercontent.com/10435269/31699489-eca1fcaa-b3f5-11e7-8ddd-d33d91e0c46b.png)

**Comment by yanhaijing** [comment]
啥也没改，我建议你把 node_moduels删除，重新安装一下，我安装完，直接跑的

**Comment by horou-sk** [comment]
还是运行不起。。Orz

**Comment by yanhaijing** [comment]
你是 windows还是mac？

**Comment by horou-sk** [comment]
windows10

**Comment by yanhaijing** [comment]
我猜有可能windows有问题，等我去虚拟机里试试，不过我是win7

**Comment by yanhaijing** [comment]
找到原因了，https://github.com/yanhaijing/template-loader

  $ npm install --save template_js@0.6.1 # 安装template运行时
  $ npm install --save templatejs-loader # 安装template编译插件

**Comment by horou-sk** [comment]
还是会报这个错误。。..   /(ㄒoㄒ)/~~

**Comment by yanhaijing** [comment]
那我也不知道咋回事了，我这win7和mac都是好的。。。

**Comment by yanhaijing** [comment]
真的真的十分抱歉，你把demo.tmpl里面的内容都删掉试试呢

**Comment by yanhaijing** [comment]
最终怎么解决的？还是换了其它的？

**Comment by wxlworkhard** [comment]
好体贴

**Comment by horou-sk** [comment]
后面重新创建了一个项目用就可以了，不知道咋回事。(￣▽￣)"
