### ISSUE TITLE
压缩配置有问题

### ISSUE THREAD

**Issue by yunxiange** [yanhaijing/template.js#2]
目前压缩功能只是去掉生成代码中的空白字符，没有考虑到特殊情况，如html代码中标签含有属性、class、id标志，建议优化压缩功能的正则。个人想到以下可删除空白情况：
- 每行起始和结尾的空格
- 标签之间空格，但保留IE条件注释前后的换行
- 注释，保留IE条件注释
- href="javascript:后的空白

**Comment by yanhaijing** [comment]
好的多谢，这个问题我会修复的

**Comment by yanhaijing** [comment]
开始关注这个问题
