### ISSUE TITLE
对于双层循环中的使用

### ISSUE THREAD

**Issue by Chuyue0** [yanhaijing/template.js#21]
请问下大大，循环嵌套怎么样的写法呢？第一次接触到这个模板，请指教。

**Comment by Chuyue0** [comment]
@yanhaijing

**Comment by yanhaijing** [comment]
```html
<script type="text/html">
<%for (var i = 0; i < list.length; i++) {%>
    <%for(var j = 0; j < list[i].list.length; j++) {%>
        <%=list[i].list[j].name%>
    <%}%>
<%}%>
</script>
```

**Comment by Chuyue0** [comment]
大大，感谢你的回复！
按照你给我的写法，我应用在了页面中，会出现报错，
报错如下：
<name>
RenderError
<tpl>
· <%for(var i=0;i< list.length;i++) {%>
		<tr>
			<td><%=list[i].name%></td>
			<td>
				<% if (list[i].bind_status == 1 ) { %>
					已绑定
				<%} else {%>
					未绑定
				<%}%>
		    </td>
			<td>
					<%for(var j = 0; j < list[i].dcc.length; j++) {%>
						<%=list[i].dcc[j].nickname%>
					<%}%>
		    </td>
			<td>
				<% if (list[i].bind_status == 1 ) { %>
				<a href="javascript:;" class="color41 editOpt" data-type="2">修改绑定</a>
				<%} else {%>
				<a href="javascript:;" class="color41 editOpt" data-type="1">新增绑定</a>
				<%}%>
			</td>
		</tr>
		<%}%>
<render>
·
<message>
Cannot read property 'length' of null

我想请问，第二层循环中的list对象是自定义的吗？还是使用返回数据的字段呢？
烦请大大了！
不胜感激~~

**Comment by yanhaijing** [comment]
`list[i].dcc`是一个数组吗？检查下你传入的数据，可能dcc不是数组

**Comment by Chuyue0** [comment]
是的，dcc是一个数组，里面的数据形式是：
dcc:[
    {
       nickname:'阿杰',
       dcc_id:'45'
    },{
       nickname:'艺辉',
       dcc_id:'62'
    }
]

**Comment by yanhaijing** [comment]
那你是怎么调用的呢？是下面这样吗？

```
template(tpl, {list: list})
```

**Comment by Chuyue0** [comment]
方式调用：
var tpl = template(document.getElementById('tpl').innerHTML);
var str=tpl({list:topic_data});
$('#brandbinds').html(str);

**Comment by Chuyue0** [comment]
定位显示的错误行：
第一条：var str=tpl({list:topic_data})
第二条：ajax请求的地方
第三条：数据分页的方法

**Comment by yanhaijing** [comment]
topic_data 打印出来，看看符不符合上面的格式

**Comment by Chuyue0** [comment]
打印topic_data出来符合上面说的list方式；[{ id:''127,dcc:[{}] },{}]  ....

**Comment by yanhaijing** [comment]
好吧，稍等，我在本地试试
