### ISSUE TITLE
目录结构中以数字开头会导致编译错误

### ISSUE THREAD

**Issue by shirleyMHao** [yanhaijing/template.js#23]
经过测试，目录结构中有".",会报编译错误
![image](https://user-images.githubusercontent.com/23013100/36531486-0815ec64-17f9-11e8-9952-724ecb68fc7f.png)
请问如何解决？

**Comment by yanhaijing** [comment]
目录结构中有‘.’，是指哪里有点？

**Comment by yanhaijing** [comment]
这错误看起来是严格模式下不能有0开头的数字

**Comment by shirleyMHao** [comment]
又测试了几种情况，发现是目录结构中以数字开头会编译报错。
项目根目录： D:\222.测试\web\fe_src
模板在：D:\222.测试\web\fe_src\common\components\dialog.tpl

尝试过将根目录改为以下情况都没有问题： 
1. D:\a.test\web\fe_src
2. D:\测试2\web\fe_src
改为一下情况会报错：
1. D:\2test\web\fe_src
2. D:\2测试\web\fe_src

**Comment by yanhaijing** [comment]
这个bug发现的好，我看一下
