### ISSUE TITLE
有没有类似于vue的格式化功能？

### ISSUE THREAD

**Issue by leasin** [yanhaijing/template.js#24]
找template，一般情况下，最常用的就三个功能，for循环遍历，if判断，和格式化，格式化，就是管道(可能用词不当)，举个栗子，判断后端给的type是1，2，3，1显示为yes，2显示为no，3显示为未知，类似于这种，没有在文档里找到，能提示一下么？谢谢

**Comment by leasin** [comment]
不好意思，没仔细看文档，找到了，

**Comment by yanhaijing** [comment]
找到了什么？不说一下么？看起来应该可以用函数来实现，传进去一个处理函数

**Comment by leasin** [comment]
谢谢，不好意思，没注意到`registerFunction`和`registerModifer`，现在有个问题，能帮我看一下么，另一个issue[传送门](https://github.com/yanhaijing/template.js/issues/25)
