### ISSUE TITLE
变量中有中文会出现编码问题

### ISSUE THREAD

**Issue by JasonJie** [yanhaijing/template.js#28]

**Comment by yanhaijing** [comment]
感谢反馈，我记下了，不过优先级不高
小伙子，你不一般啊，O(∩_∩)O哈哈~

**Comment by yanhaijing** [comment]
@JasonJie 2.0x 预编译版本（rollup, wepbpack, fis, gulp）已解决这个问题

**Comment by yanhaijing** [comment]
cli工具上新，欢迎尝鲜

```bash
$ npx @templatejs/cli new myapp
# 选择对应的平台
# ❯ webpack4 
#   rollup 
#   parcel 
#   fis3 
#   browserify 
#   gulp 
#   browser
```

vscode插件上新，欢迎尝试
https://marketplace.visualstudio.com/items?itemName=yanhaijing1234.templatejs
