### ISSUE TITLE
在react中如何使用

### ISSUE THREAD

**Issue by l2en** [yanhaijing/template.js#30]
因为项目涉及到使用百度鹰眼项目，其中官方鹰眼项目使用到baidutemplate模板，现整合到react项目中改如何使用？ thx

**Comment by yanhaijing** [comment]
可以在描述具体点吗？我现在的理解是在react中，要使用template，我的理解对吗？
两个思路吧

第一种：
可以使用dangerouslysetinnerhtml，把template渲染完的html片段，传给react去渲染

第二种：
局部使用react，局部使用template，两者之间互不干涉
