### ISSUE TITLE
templatejs-loader当tmpl模板文件使用CRLF换行时会出现Unexpected token ILLEGAL错误

### ISSUE THREAD

**Issue by gzw95322** [yanhaijing/template.js#33]
### templatejs-loader当tmpl模板文件使用CRLF换行时会出现Unexpected token ILLEGAL错误

windows环境, 开发软件是VSCode, 当我内容的换行方式是`CRLF`换行时会出现`Unexpected token ILLEGAL`的报错, 切换为`LF`换行方式后,正常.

![image](https://user-images.githubusercontent.com/13072291/70520705-ee85e800-1b78-11ea-8e48-6e5f88b767a8.png)

### 环境

- 系统:  window 10
- 浏览器：Chrome 78
- 版本：2.0.0
- 用到的插件: @template/runtime,  templatejs-loader, webpack4
- 其他信息

### 在线例子

**测试的代码和webpack配置均使用的loader里面提供的[webpack4的配置](https://github.com/yanhaijing/template.js/tree/master/packages/template-loader/example/local-webpack4)**

相关依赖
```json
"devDependencies": {
    "templatejs-loader": "^2.2.0"
  },
  "dependencies": {
    "@templatejs/runtime": "^2.1.0"
  }
}


```

### 其他

无

**Comment by yanhaijing** [comment]
嗯嗯，感谢反馈，templatejs 底层用的 [esprima](https://github.com/jquery/esprima)来进行js AST编译 ，上面的错误是esprima报的，我研究研究esprima是否支持 CRLF，如果不支持，我可以在传给esprima之前把 加一个参数，是否把CRLF替换为LF

**Comment by yanhaijing** [comment]
是templatejs的bug，parser未对crlf(\r\n)做处理导致的问题，2.2.1 已经修复了

**Comment by gzw95322** [comment]
👌

**Comment by yanhaijing** [comment]
cli工具上新，欢迎尝鲜

```bash
$ npx @templatejs/cli new myapp
# 选择对应的平台
# ❯ webpack4 
#   rollup 
#   parcel 
#   fis3 
#   browserify 
#   gulp 
#   browser
```

vscode插件上新，欢迎尝试
https://marketplace.visualstudio.com/items?itemName=yanhaijing1234.templatejs
