### ISSUE TITLE
请问兼容ie吗？

### ISSUE THREAD

**Issue by Dawnxiaozhao** [yanhaijing/template.js#34]
### 问题是什么

问题的具体描述，尽量详细

### 环境

- 系统: MAC 10.14.x
- 浏览器：Chrome 7.4.x
- 版本：2.0.0
- 用到的插件: template, rollup-plugin-templatejs
- 其他信息

### 在线例子

如果有请提供在线例子

### 其他

其他信息

**Comment by yanhaijing** [comment]
template.js 全系列都是兼容IE的，但是兼容IE8及以下，需要引入es5shim

**Comment by Dawnxiaozhao** [comment]
好的，非常感谢!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "颜海镜"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 下午3:53
收件人: "yanhaijing/template.js"<template.js@noreply.github.com&gt;; 
抄送: "右边&amp;#xB9;&amp;#xB3;&amp;#x2074;&amp;#xB9;&amp;#xB3;&amp;#x2076;&amp;#x2078;&amp;#xB9;&amp;#xBA;&amp;#x2077;"<1341368107@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanhaijing/template.js] 请问兼容ie吗？ (#34)




template.js 全系列都是兼容IE的，但是兼容IE8及以下，需要引入es5shim

**Comment by yanhaijing** [comment]
0.x的版本都是原生支持ie6的，2.x 由于用了ts 只能编译到 es5了，所以得依赖es5shim，o(╥﹏╥)o

**Comment by Dawnxiaozhao** [comment]
&nbsp;<%if (true) {%&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <tr&gt;<td&gt;if</td&gt;<td&gt;if 语句</td&gt;</tr&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <%}%&gt;



else if&nbsp; 和 else&nbsp; 语法怎么写




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "颜海镜"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 下午5:27
收件人: "yanhaijing/template.js"<template.js@noreply.github.com&gt;; 
抄送: "右边&amp;#xB9;&amp;#xB3;&amp;#x2074;&amp;#xB9;&amp;#xB3;&amp;#x2076;&amp;#x2078;&amp;#xB9;&amp;#xBA;&amp;#x2077;"<1341368107@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanhaijing/template.js] 请问兼容ie吗？ (#34)




0.x的版本都是原生支持ie6的，2.x 由于用了ts 只能编译到 es5了，所以得依赖es5shim，o(╥﹏╥)o

**Comment by yanhaijing** [comment]
```
<%if (1) {%>
111
<%} else {%>
222
<%}%>
```

**Comment by Dawnxiaozhao** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "颜海镜"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 下午5:36
收件人: "yanhaijing/template.js"<template.js@noreply.github.com&gt;; 
抄送: "右边&amp;#xB9;&amp;#xB3;&amp;#x2074;&amp;#xB9;&amp;#xB3;&amp;#x2076;&amp;#x2078;&amp;#xB9;&amp;#xBA;&amp;#x2077;"<1341368107@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanhaijing/template.js] 请问兼容ie吗？ (#34)



<%if (1) {%&gt; 111 <%} else {%&gt; 222 <%}%&gt;

**Comment by L532J511X008** [comment]
> template.js 全系列都是兼容IE的，但是兼容IE8及以下，需要引入es5shim

ie9为啥报错 template.js error

**Comment by yanhaijing** [comment]
@L532J511X008 发一下报错信息看看？然后你用的是什么版本？

**Comment by L532J511X008** [comment]
您好，yan
您看啊...
&nbsp;<script src="/js/date.js"&gt;</script&gt;这个是引入一个外部js函数...formatDate
<span class="e-inquiry-item-content" title='<%:= formatDate(inquirys[i].ExpireTime, "yyyy-MM-dd hh:mm")%&gt;'&gt;<%:= formatDate(inquirys[i].ExpireTime, "yyyy-MM-dd hh:mm")%&gt;</span&gt;

然后，我就在模板字符串进行引入吖...
结果谷歌是没有问题的...
ie浏览器一直是报formatDate未定义...这是怎么了&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanhaijing/template.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午4:44
收件人:&nbsp;"yanhaijing/template.js"<template.js@noreply.github.com&gt;;
抄送:&nbsp;"ϺϺ"<2518450374@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yanhaijing/template.js] 请问兼容ie吗？ (#34)





 
@L532J511X008 发一下报错信息看看？然后你用的是什么版本？
