### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by User-Name-Chao** [yanhaijing/template.js#38]
### 问题是什么

不能动态给标签追加各种属性吗？在哪都没找到相关问题。

### 环境

- 系统: MAC 10.14.x
- 浏览器：Chrome 7.4.x
- 版本：2.0.0
- 用到的插件: template, rollup-plugin-templatejs
- 其他信息

### 在线例子

如果有请提供在线例子

### 其他

其他信息

**Comment by yanhaijing** [comment]
可以在描述下你的需求吗？举个例子？我没太看懂

**Comment by User-Name-Chao** [comment]
<script id="child-tpl" type="text/html">
    <ul>
        <% for(i in list){ %>
        <li><%list[i].uid%> <%=list[i].uname%></li>
        <% } %>
    </ul>
</script>
给li标签动态添加一些属性

**Comment by yanhaijing** [comment]
添加属性可以，例子如下：
```
<script id="child-tpl" type="text/html">
    <ul>
        <% for(i in list){ %>
        <li data-id="<%=xxx%>"><%list[i].uid%> <%=list[i].uname%></li>
        <% } %>
    </ul>
</script>
```

事件最好是单独绑定，使用事件代理，jq事件代理举例
```js
$(document).delegate('ul li', () => {
    // xxx
})
```

**Comment by yanhaijing** [comment]
cli工具上新，欢迎尝鲜

```bash
$ npx @templatejs/cli new myapp
# 选择对应的平台
# ❯ webpack4 
#   rollup 
#   parcel 
#   fis3 
#   browserify 
#   gulp 
#   browser
```

vscode插件上新，欢迎尝试
https://marketplace.visualstudio.com/items?itemName=yanhaijing1234.templatejs
