### ISSUE TITLE
请问这个数据为什么渲染不进去呢？

### ISSUE THREAD

**Issue by gcshine** [yanhaijing/template.js#44]
### 问题是什么

模板未渲染数据到html
### 环境

- 系统: win10
- 浏览器：版本 84.0.4147.89（正式版本） （64 位）

- 版本：v1
- 用到的插件: template.js 
- 其他信息

### 在线例子
<body>
    <div id="wp"></div>
    <script id="tpl" type="text/html">
        <div class="br ml20 mt20 fl" style="height: 447px; width: 452px;">
            <p><span class="gray size18 ml40">单元 : </span><span class="white size18"><%data[0].device_peril%></span></p>
            <p><span class="gray size18 ml40">上报人员 : </span><span class="yellow size18"></span></p>
            <p><span class="gray size18 ml40">维保内容 : </span><span class="yellow size18"></span></p>
            <p><span class="gray size18 ml40">位置 : </span><span class="white size18"></span></p>
            <p><span class="gray size18 ml40">处理状态 : </span><span class="white size18"></span></p>
            <p><span class="gray size18 ml40">上报时间 : </span><span class="white size18"></span></p>
            <p><span class="gray size18 ml40">处理时间 : </span><span class="white size18"></span></p>
            <p><span class="gray size18 ml40">执行人 : </span><span class="white size18"></span></p>
        </div>
    </script>
</body>
let data = [
    {
        device_peril:'检修0',
        peril_level:'一级',
        peril_description:'一期化学除盐',
        peril_area:'隐患地点',
        discover_time:'2020-8-27 15:44:34',
        rectify_person:'周宁',
        plan_rectify_time: '2020-8-28 15:48:16',
        check_time:'2020-8-27 15:49:01'
    }]
var html = template(document.getElementById('tpl').innerHTML,{device_peril:'1111'});
document.getElementById('wp').innerHTML = html;

### 其他

其他信息

**Comment by yanhaijing** [comment]
```html
<%data[0].device_peril%>
```
这个数据的输出，请确保输入是

```js
const data = [{device_peril: 111}, {device_peril: 222}]
template('xxx', {data: data}) // 是这样
template('xxx', data) // 不是这样
```

**Comment by gcshine** [comment]
OK 3Q
