### ISSUE TITLE
template-loader在webpack5下如何配置

### ISSUE THREAD

**Issue by fans3500** [yanhaijing/template.js#62]
### template-loader在webpack5下如何配置

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[2] has an unknown property 'query'. These properties are valid:
   object { assert?, compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }
   -> A rule description with conditions and effects for modules.

**Comment by yanhaijing** [comment]
webpack发展好快😄

**Comment by yanhaijing** [comment]
https://github.com/yanhaijing/template.js/tree/master/packages/template-loader/example/local-webpack5
webpack5的例子看这里
